services:
  postgres:
      image: postgres:alpine
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=123456
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 2s
        retries: 15
